// invitados.js
window.invitados = {
  '1': { nombre: 'Sara Flores', pases: 1 },
  '2': { nombre: 'Marina Barrios', pases: 1 },
  '3': { nombre: 'Avril Del padre', pases: 1 },
  '4': { nombre: 'Adriana Fonseca', pases: 1 },
  '5': { nombre: 'Katia (mofin) Valladares', pases: 1 },
  '6': { nombre: 'Bianca Marroquin', pases: 1 },
  '7': { nombre: 'Sophia Porras', pases: 1 },
  '8': { nombre: 'Camila Mejia', pases: 0 },
  '9': { nombre: 'Shophi Osorio', pases: 1 },
  '10': { nombre: 'Heller Estrada', pases: 1 },
  '11': { nombre: 'Juan Fernando Barrios', pases: 1 },
  '12': { nombre: 'Nicolas Carrasco', pases: 1 },
  '13': { nombre: 'Pamela Alvarado', pases: 1 },
  '14': { nombre: 'Luna Alonso', pases: 1 },
  '15': { nombre: 'Mari Ines Gonzalez', pases: 1 },
  '16': { nombre: 'Sophia Morales', pases: 1 },
  '17': { nombre: 'Karla Valdez', pases: 1 },
  '18': { nombre: 'María andre Castellon', pases: 1 },
  '19': { nombre: 'Priscilla Anico', pases: 1 },
  '20': { nombre: 'Giselle Daniels', pases: 1 },
  '21': { nombre: 'Lucia', pases: 2 },
  '22': { nombre: 'Genesei Fuentes', pases: 1 },
  '23': { nombre: 'Brittany', pases: 1 },
  '24': { nombre: 'Eunices', pases: 1 },
  '25': { nombre: 'Fer', pases: 1 },
  '26': { nombre: 'Eileen', pases: 1 },
  '27': { nombre: 'Lilian', pases: 1 },
  '28': { nombre: 'Camila', pases: 1 },
  '29': { nombre: 'Frida', pases: 1 },
  '30': { nombre: 'Marco Tulio Aguilar', pases: 2 },
  '31': { nombre: 'Familia Aguilar Nadalini', pases: 4 },
  '32': { nombre: 'Estuardo Aguilar y Familia', pases: 3 },
  '33': { nombre: 'Gabriela y Enrique', pases: 2 },
  '34': { nombre: 'Familia Velasquez Mancilla', pases: 2 },
  '35': { nombre: 'Oscar Moran y familia', pases: 3 },
  '36': { nombre: 'Renato Moran y Esposa', pases: 2 },
  '37': { nombre: 'Familia Polania Aguilar', pases: 3 },
  '38': { nombre: 'Dr Alejandro Bailey', pases: 2 },
  '39': { nombre: 'Karin Sofia Wolmers', pases: 2 },
  '40': { nombre: 'Andrea Sanchez', pases: 2 },
  '41': { nombre: 'Familia Merida Ruano', pases: 4 },
  '42': { nombre: 'Familia Rivera Sierra', pases: 4 },
  '43': { nombre: 'Gilda Walter e Hijas', pases: 3 },
  '44': { nombre: 'Familia Beteta', pases: 4 },
  '45': { nombre: 'Familia Moscoso Juarez', pases: 3 },
  '46': { nombre: 'Enrrique e Ilse', pases: 2 },
  '47': { nombre: 'Jorge Nadalini y señora', pases: 2 },
  '48': { nombre: 'Melani y Martin', pases: 2 },
  '49': { nombre: 'Alfredo Arias y Señora Arias', pases: 2 },
  '50': { nombre: 'Edgar Espinosa y Señora', pases: 2 },
  '51': { nombre: 'Mario Gaitan y Señora', pases: 2 },
  '52': { nombre: 'Familia Ng Pac', pases: 3 },
  '53': { nombre: 'Familia Lopez', pases: 2 },
  '54': { nombre: 'Hector Valladarez', pases: 2 },
  '55': { nombre: 'Diego Pedreros y señora', pases: 3 },
  '56': { nombre: 'Maren Egedorf', pases: 2 },
  '57': { nombre: 'Adriana Moreno', pases: 2 },
  '58': { nombre: 'Analin Velasquez y familia', pases: 2 },
  '59': { nombre: 'Carlos Cardenas y Familia', pases: 5 },
  '60': { nombre: 'Carlos Mejia y Familia', pases: 3 },
  '61': { nombre: 'Paola Andrea Sosa', pases: 1 },
  '62': { nombre: 'María Adelaida', pases: 1 },
  '63': { nombre: 'Andrey y Lorena', pases: 2 },
  '64': { nombre: 'Felipe Cardenas y Familia', pases: 3 },
  '65': { nombre: 'Guillermo Cardoso y Familia', pases: 4 },
  '66': { nombre: 'Juan Diego Cardoso', pases: 1 },
  '67': { nombre: 'Edgar Sosa y Señora', pases: 2 },
  '68': { nombre: 'Arturo Mateus y Señora', pases: 2 },
  '69': { nombre: 'Nestor Cardoso y Señora', pases: 2 },
  '70': { nombre: 'Aramis Pendland', pases: 2 },
};

